### ISSUE TITLE
Will not run on Ubuntu 22.04

### ISSUE THREAD

**Issue by ndgrossman** [beatngu13/pdf-zoom-wizard#478]
### Expected Behavior

Upon running the executable, the GUI should appear, as it did in v0.11.0.

### Actual Behavior

Nothing happens.

### Steps to Reproduce

Try to execute in Terminal, for example.  When doing so, the following is generated:

### Log

Exception in thread "main" com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public void ch.qos.logback.core.encoder.LayoutWrappingEncoder.setCharset(java.nio.charset.Charset)
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
	at java.lang.reflect.Method.acquireMethodAccessor(Method.java:77)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:126)
	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:96)
	at ch.qos.logback.core.model.processor.ImplicitModelHandler.doBasicProperty(ImplicitModelHandler.java:111)
	at ch.qos.logback.core.model.processor.ImplicitModelHandler.handle(ImplicitModelHandler.java:86)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:241)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.secondPhaseTraverse(DefaultProcessor.java:253)
	at ch.qos.logback.core.model.processor.DefaultProcessor.traversalLoop(DefaultProcessor.java:90)
	at ch.qos.logback.core.model.processor.DefaultProcessor.process(DefaultProcessor.java:106)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.processModel(GenericXMLConfigurator.java:208)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:170)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:122)
	at ch.qos.logback.core.joran.GenericXMLConfigurator.doConfigure(GenericXMLConfigurator.java:65)
	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configureByResource(DefaultJoranConfigurator.java:68)
	at ch.qos.logback.classic.util.DefaultJoranConfigurator.configure(DefaultJoranConfigurator.java:35)
	at ch.qos.logback.classic.util.ContextInitializer.invokeConfigure(ContextInitializer.java:122)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:97)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:65)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initializeLoggerContext(LogbackServiceProvider.java:52)
	at ch.qos.logback.classic.spi.LogbackServiceProvider.initialize(LogbackServiceProvider.java:41)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:183)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:170)
	at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:455)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:441)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:390)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:416)
	at com.github.beatngu13.pdfzoomwizard.Launcher.<clinit>(Launcher.java:17)
	at com.github.beatngu13.pdfzoomwizard.LauncherWrapper.main(LauncherWrapper.java:9)

### Environment

- OS: Ubuntu 22.04
- PDF Zoom Wizard version: 0.12.0

**Comment by beatngu13** [comment]
Relates to: https://github.com/gluonhq/substrate/issues/1130

**Comment by beatngu13** [comment]
Closed via #479.

Fix is released in [0.12.1](https://github.com/beatngu13/pdf-zoom-wizard/releases/tag/v0.12.1). Feel free to reopen this issue if you still encounter problems.

Happy new year! 🥳
