### ISSUE TITLE
PDF version 1.5 yields RuntimeException

### ISSUE THREAD

**Issue by beatngu13** [beatngu13/pdf-zoom-wizard#483]
### Expected Behavior

[This PDF](https://github.com/beatngu13/pdf-zoom-wizard/files/13805583/Old_._New_Testament.pdf) can be modified to set its bookmarks to "Fit width".

### Actual Behavior

A `RuntimeException` is thrown:

```text
java.lang.RuntimeException: Invalid PDF version format: '^(\d+)\.(\d+)$' pattern expected.
	at org.pdfclown.Version.get(Version.java:72)
	at org.pdfclown.Version.get(Version.java:62)
	at org.pdfclown.documents.Document.getVersion(Document.java:539)
	at org.pdfclown.objects.PdfObjectWrapper.checkCompatibility(PdfObjectWrapper.java:358)
	at org.pdfclown.documents.Document.access$1(Document.java:1)
	at org.pdfclown.documents.Document$Configuration.setXrefMode(Document.java:166)
	at org.pdfclown.files.File.<init>(File.java:192)
	at org.pdfclown.files.File.<init>(File.java:171)
	at com.github.beatngu13.pdfzoomwizard.core.Wizard.modifyFile(Wizard.java:132)
```

### Steps to Reproduce

If possible, please provide a sample PDF and describe the steps to reproduce the behavior:

1. Select the aforementioned PDF
2. Uncheck "Copy"
3. Select "Fit width"
4. Click on "Run"
5. "Success" is reported, although the PDF is not modified
6. The log file shows a `RuntimeException` is thrown

Debugging shows that the PDF version 1.5 is converted to 1#2E5, which yields the exception in `org.pdfclown.Version`.

### Log

[log.txt](https://github.com/beatngu13/pdf-zoom-wizard/files/13805582/log.txt)

### Environment

- OS: macOS 13.5.2
- PDF Zoom Wizard version: 0.13.0

**Comment by beatngu13** [comment]
@idsks555 while I'm further investigating the underlying issue, here's the converted PDF (fit width):

[Old_._New_Testament-FIT-WIDTH.pdf](https://github.com/beatngu13/pdf-zoom-wizard/files/13843011/Old_._New_Testament-FIT-WIDTH.pdf)
